language: python
dist: xenial
cache: pip
matrix:
  include:
    - python: 3.7-dev
      env: TOXENV=py37-asyncio,py37-uvloop
    - python: 3.8-dev
      env: TOXENV=py38-asyncio,py38-uvloop
    - python: 3.9-dev
      env: TOXENV=py39-asyncio,py39-uvloop
    - python: 3.10-dev
      env: TOXENV=py310-asyncio,py310-uvloop
    - python: 3.11-dev
      env: TOXENV=py310-asyncio,py310-uvloop

  allow_failures:
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - python: 3.9-dev
    - python: 3.10-dev
    - python: 3.11-dev

script: tox
install:
  - "pip install --upgrade pip"
  - "pip install --upgrade poetry"
  - "pip install --upgrade tox tox-venv"
