version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  circleci_py38:
    docker:
      - image: "cimg/python:3.8"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
  py37:
    docker:
      - image: "python:3.7-slim-bullseye"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
  py38:
    docker:
      - image: "python:3.8-slim-bullseye"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
  py39:
    docker:
      - image: "python:3.9-slim-bullseye"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
  py310:
    docker:
      - image: "python:3.10-slim-bullseye"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
  pypy3:
    docker:
      - image: "pypy:3-slim-bullseye"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small

commands:
  python_version:
    description: "Output Python version"
    steps:
      - run:
          command: python -V
          name: "Checking python version"

  tox:
    description: "Run tox"
    steps:
      - restore_cache:
          name: "Restoring cache"
          keys:
            - tox-v6-{{ .Environment.CIRCLE_JOB }}-{{ checksum "tox.ini" }}
            - tox-v6-{{ .Environment.CIRCLE_JOB }}-
      - run:
          command: pip install --upgrade tox
          name: "Installing tox"
          environment:
            XDG_CACHE_HOME: "/tmp/cache"
      - run:
          command: tox --workdir /tmp/toxworkdir --installpkg dist/aiosmtplib-*.whl
          name: "Running tox"
          environment:
            XDG_CACHE_HOME: "/tmp/cache"
      - save_cache:
          name: "Updating cache"
          key: tox-v6-{{ .Environment.CIRCLE_JOB }}-{{ checksum "tox.ini" }}
          paths:
            - /tmp/toxworkdir
            - /tmp/cache/pip

jobs:
  lint:
    executor: py38
    steps:
      - python_version
      - checkout
      - restore_cache:
          name: "Restoring pre-commit cache"
          keys:
            - pre-commit-v4-{{ checksum ".pre-commit-config.yaml" }}
            - pre-commit-v4-
      - tox
      - save_cache:
          name: "Updating pre-commit cache"
          key: pre-commit-v4-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /tmp/cache/pre-commit
    environment:
      TOXENV: lint

  docs:
    executor: py38
    environment:
      TOXENV: docs
    steps:
      - python_version
      - checkout
      - attach_workspace:
          at: dist
      - tox

  build:
    executor: circleci_py38
    environment:
    steps:
      - python_version
      - checkout
      - run:
          name: Building packages
          command: poetry build -vv
      - run:
          name: Install Twine
          command: poetry add --dev twine
      - run:
          name: Twine check
          command: poetry run twine check dist/*
      - persist_to_workspace:
          root: dist
          paths:
            - aiosmtplib-*.tar.gz
            - aiosmtplib-*.whl
      - store_artifacts:
          path: dist/

  test:
    executor: <<parameters.executor_name>>
    parameters:
      executor_name:
        type: string
        description: "executor name"
      toxenv:
        type: string
        description: "tox env name"
    environment:
      COVERAGE_FILE: "coverage-results/.coverage.<<parameters.executor_name>>"
      HYPOTHESIS_PROFILE: "ci"
      BIND_ADDR: "127.0.0.1"
      TOXENV: "<<parameters.toxenv>>"
    steps:
      - python_version
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          name: "Restoring hypothesis database"
          keys:
            - "hypothesis-v3-<<parameters.executor_name>>"
      - tox
      - save_cache:
          name: "Updating hypothesis database"
          key: "hypothesis-v3-<<parameters.executor_name>>"
          paths:
            - ~/project/.hypothesis
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: coverage-results
          paths:
            - .coverage.*

  coverage:
    executor: py38
    environment:
      TOXENV: coverage
    steps:
      - python_version
      - checkout
      - attach_workspace:
          at: coverage-results
      - run:
          name: "Copy coverage results from workspace"
          command: cp coverage-results/.coverage.* ./
      - tox
      - store_artifacts:
          path: coverage.xml
      - store_artifacts:
          path: htmlcov
      - codecov/upload:
          file: coverage.xml

  deploy_to_pypi:
    executor: circleci_py38
    steps:
      - python_version
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Uploading to Test PyPI
          command: |
            poetry config repositories.testpypi https://test.pypi.org/simple
            poetry publish -vv --repository testpypi --username $TESTPYPI_USERNAME --password $TESTPYPI_PASSWORD
      - run:
          name: Uploading to PyPI
          command: poetry publish -vv --username $PYPI_USERNAME --password $PYPI_PASSWORD

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint:
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - build:
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - lint
            - build
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - test:
          name: "test-py37"
          executor_name: py37
          toxenv: "py37-asyncio,py37-uvloop"
          requires:
            - lint
            - build
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - test:
          name: "test-py38"
          executor_name: py38
          toxenv: "py38-asyncio,py38-uvloop"
          requires:
            - lint
            - build
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - test:
          name: "test-py39"
          executor_name: py39
          toxenv: "py39-asyncio,py39-uvloop"
          requires:
            - lint
            - build
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - test:
          name: "test-py310"
          executor_name: py310
          toxenv: "py310-asyncio,py310-uvloop"
          requires:
            - lint
            - build
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - test:
          name: "test-pypy3"
          executor_name: pypy3
          toxenv: "pypy3-asyncio"
          requires:
            - lint
            - build
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - coverage:
          requires:
            - test-py37
            - test-py38
            - test-py39
            - test-py310
            - test-pypy3
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.*/
      - deploy_to_pypi:
          requires:
            - build
            - lint
            - docs
            - test-py37
            - test-py38
            - test-py39
            - test-py310
            - test-pypy3
          context:
            - docker-hub-credentials
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
